language: csharp
solution: COSE.Std10.sln

matrix:
  include:
    - dotnet: 3.1
      mono: none
      env:
        - SLN=COSE.Std10.sln
          TARGET=Std10
          VERSION=Release
          NUGET=dotnet
          FRAMEWORK=netcoreapp2.0
      os: osx
    - dotnet: 3.1
      mono: none
      env:
        - SLN=COSE.Std10.sln
          TARGET=Std10
          VERSION=Release
          NUGET=dotnet
          FRAMEWORK=netcoreapp2.0
      os: linux
    - dotnet: 2.1
      mono: none
      env:
        - SLN=COSE.Std10.sln
          TARGET=Std10
          VERSION=Release
          NUGET=dotnet
          FRAMEWORK=netcoreapp2.0
      os: linux

install:
#   - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
#   - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner
   - git clone --depth 1 https://github.com/cose-wg/Examples Regressions
   - git clone --depth 1 https://github.com/ietf-jose/cookbook cookbook
   - ls
   - ls COSE
#   - nuget restore COSE/COSE.Std10.sln
   
script:
  - ./build.sh
