language: csharp
mono:
  - latest

env:
   - SLN=COAP.Net40.sln
     TARGET=Net40
     VERSION=Release
   - SLN=COAP.Net45.sln
     TARGET=Net45
     VERSION=Release
   - SLN=COAP.Std10.sln
     TARGET=Std10
     VERSION=Release


install:
   - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner
   - git clone --depth 1 https://github.com/cose-wg/Examples Regressions
   - git clone --depth 1 https://github.com/ietf-jose/cookbook cookbook
   
script:
  - ./build.sh
