language: csharp
mono:
  - latest
solution: examples/examples.sln
script:
  - git clone --depth 1 git://github.com/cose-wg/Examples Regressions
  - xbuild /p:Configuration=Release examples/examples.sln
  - ls
  - ls examples
  - examples/bin/Release/Examples.exe Regressions
  