language: csharp

matrix:
  include:
#    - dotnet: 2.1.2
#      mono: none
#      env:
#        - SLN=COSE.Std10.sln
#          TARGET=Std10
#          VERSION=Release
#          NUGET=dotnet
#      os: linux
    - mono: latest
      env:
        - SLN=COSE.Std10.sln
          TARGET=Std10
          VERSION=Release
          NUGET=../nuget.exe
      os: linux
    - mono: latest
      env:
        - SLN=COSE.Std10.sln
          TARGET=Std10
          VERSION=Debug
          NUGET=../nuget.exe
      os: linux
    - mono: 5.14.0
      env:
        - SLN=COSE.Std10.sln
          TARGET=Std10
          VERSION=Debug
          NUGET=../nuget.exe
      os: linux
    - mono: latest
      env:
        - SLN=COSE.Std10.sln
          TARGET=Std10
          VERSION=Release
          NUGET=../nuget.exe
      os: osx

install:
#   - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
   - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner
   - git clone --depth 1 https://github.com/cose-wg/Examples Regressions
   - git clone --depth 1 https://github.com/ietf-jose/cookbook cookbook
   - nuget restore COSE.Std10.sln
   
script:
  - ./build.sh
