language: csharp

os: 
  - linux
  - osx

matrix:
  include:
    - dotnet: 2.1.2
      mono: none
      env:
        - SLN=COSE.Std10.sln
          TARGET=Std10
          VERSION=Release
    - mono: latest
      env:
        - SLN=COSE.Std10.sln
          TARGET=Std10
          VERSION=Release

install:
   - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
   - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner
   - git clone --depth 1 https://github.com/cose-wg/Examples Regressions
   - git clone --depth 1 https://github.com/ietf-jose/cookbook cookbook
   
script:
  - ./build.sh
