language: csharp
mono:
- latest
dist: trusty

env:
#   - SLN=COSE.Net40.sln
#     TARGET=Net40
#     VERSION=Release
#   - SLN=COSE.Net45.sln
#     TARGET=Net45
#     VERSION=Release
   - SLN=COSE.Std10.sln
     TARGET=Std10
     VERSION=Release


install:
   - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
   - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner
   - git clone --depth 1 https://github.com/cose-wg/Examples Regressions
   - git clone --depth 1 https://github.com/ietf-jose/cookbook cookbook
   
script:
  - ./build.sh
