version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2-sdk

    working_directory: ~/repo

    steps:
       - checkout

       - run:
         name: Unit Tests
         command: dotnet cose\COSE.Std10.sln
